// examples/src/hello.zig
const std = @import("std");
const zttp = @import("zttp");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const options = zttp.ServerOptions{
        .port = 8080,
    };

    var bundle = try zttp.createServer(allocator, options);
    defer bundle.deinit();

    // Add default logging middleware
    // try bundle.use(zttp.Middleware.log);
    try bundle.use(zttp.Middleware.htmx);

    // Load routes
    try bundle.loadRoutes(@import("AutoGenerated.zig").getRoutes);
    // make a load templates function...
    // Load templates
    try bundle.loadTemplates(@import("AutoGenerated.zig").getTemplates);

    std.log.info("Starting server on :8080", .{});
    try bundle.start(true);
}
