const std = @import("std");
const zttp = @import("zttp");
const chat_ws = @import("routes/demos/websocket/chat/ws.zig"); // Import WebSocket module

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const options = zttp.ServerOptions{
        .port = 8088,
    };

    var bundle = try zttp.createServer(allocator, options);
    defer bundle.deinit();

    // Initialize the chat WebSocket module
    try chat_ws.init(allocator);
    defer chat_ws.deinit();

    // Add default logging middleware
    // try bundle.use(zttp.Middleware.log);
    try bundle.use(zttp.Middleware.static);
    try bundle.use(zttp.Middleware.htmx);

    // Load routes
    try bundle.loadRoutes(@import("AutoGenerated.zig").getRoutes);
    // Load templates
    try bundle.loadTemplates(@import("AutoGenerated.zig").getTemplates);

    try bundle.start(true);
}
